### ISSUE TITLE
Problems trying to run the bot locally

### ISSUE THREAD

**Issue by Ephrem-Adugna** [jbelford/Eolian#21]
Hi,
I was trying to run the bot locally on my own machine, and it doesn't seem working. Are there any steps I need to follow to get it running?

**Comment by jbelford** [comment]
Hey there! I haven't really got around to including steps for self-hosting.
But it should be pretty simple - assuming you have node 14+
Just clone the repo - npm install, npm run build, npm start

Of  course, there's a bunch of environment variables that need to be setup and I'll leave that up to you to figure out
The names of which are all located in https://github.com/jbelford/Eolian/blob/master/src/common/env.ts
