### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by KDropZ** [jbelford/Eolian#29]
If I'm not wrong there is no 24/7 option, ueueloop option or shuffle option through commands. Both would be awesome for a playlist to play 24/7 in shuffle mode:)

**Comment by jbelford** [comment]
Hey KDrop2, there is indeed a way to shuffle, although it does seem to be easily missed so I might change this.

Anyway the shuffle command is part of the `list` command.

use `!list shuffle` or `!list -shuffle` (if using flag syntax). Additionally you can click the shuffle button when bringing up the queue using `!list`.

The unending loop is an idea worth considering. Though I don’t have any plans to support 24/7

**Comment by jbelford** [comment]
Added !loop command
