### ISSUE TITLE
.list command is broken, there is no clear all songs command.

### ISSUE THREAD

**Issue by Mintedcopper** [jbelford/Eolian#31]
.list shows a bunch of songs that I never added and didn't play
the lack of ability to clear all songs is very painful

love the bot!

**Comment by Mintedcopper** [comment]
is a loop command planned for the future?

**Comment by jbelford** [comment]
Hi Minted, can you describe what commands you executed that added extra songs?

The queue can be cleared by providing `clear` keyword.

Use `list clear` (or `list -clear` if server is using flag-based) to clear the queue.

I might change this in future because it seems to be hard to find

**Comment by jbelford** [comment]
In addition, if you would like to remove a range of songs you can take a look at the `remove` command. Take a look at the examples using `help remove`

**Comment by Mintedcopper** [comment]
at the time this message was sent, the bot was added 10 mins or so ago and we had only played a few songs, none of which were the seemingly random selection of yearly 2000s music that the .list command had displayed.
(unrelated bug)
In the music channel we had created, the bot could add songs and use all of the normal commands but it could not display app commands and the context menus associated. in other servers the context menus worked fine and in the general section of the same server this also worked fine, all the settings in all 3 places are identical and the general/music channels were synced.
as this is a very puzzling and seemingly random issue I don't expect any fixes for this, just reporting the issue.

**Comment by Mintedcopper** [comment]
as for the remove command
"Eolian
BOT
 — Today at 2:03 PM
@ghost of Jim, You must provide TOP, BOTTOM, or NEXT keywords so I know what you wanted to remove!"
this is the reply I get when I use the command, NEXT works fine removing the next song in the queue but "top" and "bottom" seem to do nothing, with caps and with no caps.

**Comment by Mintedcopper** [comment]
to clarify TOP and BOTTOM give me the same error

**Comment by Mintedcopper** [comment]
although !list clear works fine

**Comment by Mintedcopper** [comment]
UPDATE:
the !list issue fixed it self? i don't really know how but it just did.
problems that remain
1. !remove (TOP/BOTTOM) not working
2. the weird music channel issue that i don't expected to be fixed

**Comment by jbelford** [comment]
Use `help top` or `help bottom`. The examples show how to use this correctly, you need to provide a range after you specify. Ex: `top 10` or `top 10:12`. The former will indicate the top 10 items, and latter will indicate the 10th to the 12th items.

**Comment by Mintedcopper** [comment]
oh thank you

**Comment by jbelford** [comment]
ALso make sure that the bot has send permissions to that new channel you created. I checked logs and am seeing errors regarding permissions which is probably the reason. Normally the bot will send you a DM if it has issues sending somewhere but there might be a bug here for why it can't send

**Comment by jbelford** [comment]
There seems to be issues with bing api's cert. Added fix to fallback to youtube for time being. Also fixed issue where errors occur starting the stream, the player stops working.
