### ISSUE TITLE
What goes in PROD in env.ts 

### ISSUE THREAD

**Issue by ninjaninja140** [jbelford/Eolian#37]
Title says it all, and yes. It’s me again.

**Comment by ninjaninja140** [comment]
Becuase it always says it’s supposed to be some sort of env but I don’t understand it and what it means

**Comment by ninjaninja140** [comment]
actually @jbelford i have live share on my VS studio if you want to come and have a look at the env script to see if anything is wrong

**Comment by jbelford** [comment]
Take a look at th env.ts file. PROD is a boolean env so it needs to be either `true` or `false`. For self-hosting just set it to `true` unless you want to see debug logs
https://github.com/jbelford/Eolian/wiki/How-to-run
