### ISSUE TITLE
Please ADD An Replit

### ISSUE THREAD

**Issue by Rexx0003** [jbelford/Eolian#42]
Please ADD An Replit I Really Dont Know How To Start This Files In My Server Normally The bot Files Has index.js but in this how i dont know so please add an replit

**Comment by jbelford** [comment]
I am sorry I don't know anything about replit. This project is relatively environmentally agnostic though as long as it either supports docker OR typescript with ffmpeg support. See https://github.com/jbelford/Eolian/wiki/How-to-run
